version: '3.8'

services:
  p115-share:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: p115-share
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./avatars:/app/backend/static/avatars
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped
