version: '3.8'

services:
  p115-share:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: p115-share
    ports:
      - "8000:8000"
    volumes:
      - ./config.json:/app/config.json
      - ./.env:/app/.env
    restart: unless-stopped
